name: Snyk API & Web CICD Scan

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROBELY_API_KEY: ${{ secrets.PROBELY_API_KEY }}
      TARGET_ID: ${{ vars.TARGET_ID }}

    steps:
      # Step 1: Install Probely CLI
      - name: Install Probely CLI
        run: |
          # Install Probely CLI
          pip install probely
          # Get a list of targets
          probely targets get

      # Step 2: Start scan with scan ID
      - name: Start Scan
        run: |
          # TARGET_ID=$(probely targets get -o JSON | jq -r '.[0].id')
          # Start a scan with Target ID variable and save scan ID
          SCAN_ID=$(probely targets start-scan ${{ vars.TARGET_ID }} -o JSON | jq -r '.[0].id')
          echo ${SCAN_ID}

      # Step 3: Wait for scan to end
      - name: Wait for scan to end
        run: |
          # Wait until scan ends
          while true; do
            echo "-----------------------------------"
            SCAN_STATUS=$(probely scans get ${SCAN_ID} --api-key ${{ secrets.PROBELY_API_KEY }} -o JSON | jq -r '.[0].status')
            echo $(SCAN_STATUS)
            if [ $SCAN_STATUS == "started" ] || [ $SCAN_STATUS == "queued" ]; then
              echo "Scan is running or queued!";
            else
              echo "Scan is not running... finishing"
              break;
            fi
            sleep 30;
          done
          
